name: apilorning
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  rxdart: ^0.27.5
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_svg: ^1.1.5
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.1.1
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  table_calendar: ^3.0.8






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


